# Generated by Django 3.2.6 on 2021-09-14 14:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='blog',
            new_name='blog_id',
        ),
    ]
