# Generated by Django 3.2.6 on 2021-09-15 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_rename_blog_tag_blog_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='blog_id',
            field=models.ForeignKey(db_column='blog_nid', on_delete=django.db.models.deletion.CASCADE, related_name='Article', to='blog.blog', verbose_name='所属博客'),
        ),
    ]
