# Generated by Django 3.2.6 on 2021-09-16 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_alter_tag_blog_id'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='article',
            table=None,
        ),
    ]
