# Generated by Django 3.2.6 on 2021-09-16 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_article_table'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='blog',
            new_name='blog_nid',
        ),
    ]
