# Generated by Django 3.2.6 on 2021-08-09 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('author_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='作者ID')),
                ('name', models.CharField(max_length=11, verbose_name='姓名')),
                ('age', models.IntegerField(verbose_name='年龄')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('book_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='书号')),
                ('book_name', models.CharField(default='', max_length=50, null=True, verbose_name='书名')),
                ('book_price', models.DecimalField(decimal_places=2, max_digits=7, null=True, verbose_name='价格')),
                ('book_info', models.CharField(default='', max_length=100, null=True, verbose_name='描述')),
                ('author_id', models.IntegerField(null=True, verbose_name='作者ID')),
            ],
        ),
    ]
