# Generated by Django 3.2.6 on 2021-08-09 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='age',
            new_name='author_age',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='email',
            new_name='author_email',
        ),
        migrations.RenameField(
            model_name='author',
            old_name='name',
            new_name='author_name',
        ),
    ]
