# Generated by Django 3.2.6 on 2021-08-09 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0004_alter_book_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
