# Generated by Django 3.2.6 on 2021-08-09 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookstore', '0005_alter_book_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_name',
            field=models.CharField(default='', max_length=50, null=True, unique=True, verbose_name='书名'),
        ),
    ]
